# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e0f1cc169b9f1927488f6b9ab04f1aa01b1562c15213675b3aca6aea6a10c78b28d5210b2643d56fa72298f124fc3e6a69aa2b18dbdfeb23d4212cd57822f7e

test:
  secret_key_base: 21e25746c292763743adc3e8b5b20e6bc4fe2c3e9bbab2d62e655eb00b2766eec0097f9b4e7629768f40bb2e411d1079336ad0c9cf3fa5950eab792fd66a620a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
